base_url = "https://stackpointer.xyz"
title = "heptanal"
description = "Projects by heptanal."
author = "heptanal"

compile_sass = false
build_search_index = false
minify_html = true

[extra]
github_url = "https://github.com/heptanal"
site_source_url = "https://github.com/heptanal/heptanal.github.io"
