base_url = "https://stackpointer.xyz"
title = "heptanal"
description = "Small, self-hosted software by heptanal."
author = "heptanal"

compile_sass = false
build_search_index = false
minify_html = true

[extra]
github_url = "https://github.com/heptanal"
